### PR TITLE
enforce spacing for curly braces with eslint

### PR DESCRIPTION
**Pull request by earnubs**
Did you know you can: eslint -c .eslintrc.js '**/*.js' --fix and magic happens?

### CODE REVIEW

**Comment by bartaz** [comment]
Some magic didn't happen? It seems that there are still lint errors in containers/app.js

**Comment by earnubs** [comment]
I am hurt by the partial application of magic :(

**Comment by earnubs** [comment]
I had not merged latest locally, and travis is running the test against merged head? TIL

**Comment by bartaz** [comment]
Good to go. 👍

**Pull request merged**
