### PR TITLE
22: Add PostCSS

### PR DESCRIPTION
**Pull request by katiefenn**
- Added PostCSS pre-processor
- Added postcss-simple-vars plugin

### CODE REVIEW

**Comment by katiefenn** [comment]
I've removed the postcss-import plugin, because it seems too powerful to use with CSS Modules.

The original reason for including it was to use it to import variables from other files, like you can in Sass. But postcss-import also allows you to import rules from other files, which undermines the modularity of CSS Modules.

postcss-simple-vars allows the injection of variables into stylesheets, but this will be managed in configuration instead.

**Comment by earnubs** [comment]
Could you add autoprefixer? Default setting should be fine I think?

**Comment by bartaz** [comment]
So without postcss-import modules don't have any access to other CSS?

I wonder how it affects possibility of using [class composition](https://github.com/css-modules/css-modules#composition). For example having some shared base classes defined and modules using them to compose local styles?

But maybe I'm trying to solve the problem that we don't have (yet).

**Comment by katiefenn** [comment]
bartaz: That's it exactly - I'd prefer to encourage using the class composition feature in CSS Modules instead of importing rules like we do in Sass. I'm concerned that doing so risks bloating the CSS bundle file.

**Comment by bartaz** [comment]
@katiefenn So can you compose from a class outside of current module without importing it? Assuming it will be global maybe? I haven't used that, so I'm not sure how it works in practice. Maybe it will be clearer once we have some components code to work with.

**Comment by katiefenn** [comment]
bartaz: Yes. It works differently to Sass's global importing.

Say `.rule-a` composes `.rule-b`: wherever the `.rule-a` className is added to an element, CSS Modules will automatically add the `.rule-b` className too, ensuring that the element inherits the styles from both rules.

**Comment by earnubs** [comment]
🛳

**Comment by bartaz** [comment]
@katiefenn Right! I knew that it adds class names to elements, but for some reason still thought it requires importing of some sort. Yay CSS Modules! 🎉

**Pull request merged**
